##########################################################################
#STM8 peripheral modules
#Change modules/included files from stm8l15x_conf.h. Do not edit this file
##########################################################################
 OBJS += stm8l15x_adc.rel
 OBJS += stm8l15x_aes.rel
 OBJS += stm8l15x_beep.rel
 OBJS += stm8l15x_clk.rel
 OBJS += stm8l15x_comp.rel
 OBJS += stm8l15x_dac.rel
 OBJS += stm8l15x_dma.rel
 OBJS += stm8l15x_exti.rel
 OBJS += stm8l15x_flash.rel
 OBJS += stm8l15x_gpio.rel
 OBJS += stm8l15x_i2c.rel
 OBJS += stm8l15x_irtim.rel
 OBJS += stm8l15x_itc.rel
 OBJS += stm8l15x_iwdg.rel
 OBJS += stm8l15x_lcd.rel
 OBJS += stm8l15x_pwr.rel
 OBJS += stm8l15x_rst.rel
 OBJS += stm8l15x_rtc.rel
 OBJS += stm8l15x_spi.rel
 OBJS += stm8l15x_syscfg.rel
 OBJS += stm8l15x_tim1.rel
 OBJS += stm8l15x_tim2.rel
 OBJS += stm8l15x_tim3.rel
 OBJS += stm8l15x_tim4.rel
 OBJS += stm8l15x_tim5.rel
 OBJS += stm8l15x_usart.rel
 OBJS += stm8l15x_wfe.rel
 OBJS += stm8l15x_wwdg.rel
